version: '3.9'

services:
  db:
    image: postgres:13-alpine
    container_name: climat-risk-api_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=GEODA
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=GEODA
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
    depends_on:
    - db

  frontend:
    build:
      context: ./frontend  # Path to the React app directory
    ports:
      - "3000:80"  # Map port 80 in the container to port 3000 on the host


volumes:
  postgres_data: